version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - "*"
  name: build/$CODEBUILD_BUILD_NUMBER/my-artifacts
  base-directory: build